cabal-version: 3.0
name: loomeric-prelude
version: 0.1.0.0

homepage: https://github.com/loonycyborg/loomeric
bug-reports: https://github.com/loonycyborg/loomeric/issues
license: BSD-3-Clause-Attribution

common common-options
    default-language: GHC2021
    default-extensions:
        NoImplicitPrelude

library
    import: common-options
    hs-source-dirs: src
    exposed-modules: LoomericPrelude
                     Loomeric.Algebra.Group
                     Loomeric.Algebra.Ring
                     Loomeric.Data.Conversions.Integer
                     Loomeric.Data.Conversions.Float
                     Loomeric.Data.Conversions.Rational
                     Loomeric.Data.Conversions.Partial
                     Loomeric.Data.Peano
                     Loomeric.Data.Ratio
                     Loomeric.Data.Complex
                     Loomeric.Data.Integer
                     Loomeric.Data.Vector
                     Loomeric.Algebra.Field
                     Loomeric.Algebra.Module
                     Loomeric.Algebra.VectorSpace
    build-depends: base, ghc-bignum, ghc-typelits-natnormalise, ghc-typelits-knownnat, singleton-bool, mono-traversable, generics-sop

executable example
  import: common-options
  main-is: Main.hs
  ghc-options: -threaded -O3
  build-depends: base, loomeric-prelude
  hs-source-dirs: example
